# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Cache st typings
        uses: actions/cache@v3
        with:
          key: st
          path: |
            ~/.cache/scalablytyped
            ~/.ivy2/local/org.scalablytyped
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version-file: .github/workflows/.java-version
          java-version: 23
          distribution: "temurin"
          cache: "sbt"
      - name: Setup sbt launcher
        uses: sbt/setup-sbt@v1
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: npm
      - name: Install npm deps
        run: npm install
      - name: Build with vite
        run: npm run deploy
        env:
          BASE_PATH: "/fahrtenbuch"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
